# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import alco_pb2 as alco__pb2


class CaregiverResultStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.push_result = channel.unary_unary(
                '/alco.CaregiverResult/push_result',
                request_serializer=alco__pb2.CaregiverResultPushingAction.SerializeToString,
                response_deserializer=alco__pb2.CaregiverResultPushingResponse.FromString,
                )


class CaregiverResultServicer(object):
    """The greeting service definition.
    """

    def push_result(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CaregiverResultServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'push_result': grpc.unary_unary_rpc_method_handler(
                    servicer.push_result,
                    request_deserializer=alco__pb2.CaregiverResultPushingAction.FromString,
                    response_serializer=alco__pb2.CaregiverResultPushingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alco.CaregiverResult', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CaregiverResult(object):
    """The greeting service definition.
    """

    @staticmethod
    def push_result(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alco.CaregiverResult/push_result',
            alco__pb2.CaregiverResultPushingAction.SerializeToString,
            alco__pb2.CaregiverResultPushingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
