# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alco.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='alco.proto',
  package='alco',
  syntax='proto3',
  serialized_options=b'\n#io.grpc.alco.CaregiverResultPushingB\tAlcoProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nalco.proto\x12\x04\x61lco\"\x89\x01\n\x1c\x43\x61regiverResultPushingAction\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x14\n\x0cpushing_mode\x18\x02 \x01(\t\x12\x15\n\rdelivery_time\x18\x03 \x01(\t\x12\x15\n\rdetected_time\x18\x04 \x01(\t\x12\x16\n\x0e\x64\x65tected_value\x18\x05 \x01(\x05\"8\n\x1e\x43\x61regiverResultPushingResponse\x12\x16\n\x0epushing_status\x18\x01 \x01(\x05\x32l\n\x0f\x43\x61regiverResult\x12Y\n\x0bpush_result\x12\".alco.CaregiverResultPushingAction\x1a$.alco.CaregiverResultPushingResponse\"\x00\x42\x38\n#io.grpc.alco.CaregiverResultPushingB\tAlcoProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_CAREGIVERRESULTPUSHINGACTION = _descriptor.Descriptor(
  name='CaregiverResultPushingAction',
  full_name='alco.CaregiverResultPushingAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='alco.CaregiverResultPushingAction.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pushing_mode', full_name='alco.CaregiverResultPushingAction.pushing_mode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delivery_time', full_name='alco.CaregiverResultPushingAction.delivery_time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detected_time', full_name='alco.CaregiverResultPushingAction.detected_time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detected_value', full_name='alco.CaregiverResultPushingAction.detected_value', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=158,
)


_CAREGIVERRESULTPUSHINGRESPONSE = _descriptor.Descriptor(
  name='CaregiverResultPushingResponse',
  full_name='alco.CaregiverResultPushingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pushing_status', full_name='alco.CaregiverResultPushingResponse.pushing_status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=216,
)

DESCRIPTOR.message_types_by_name['CaregiverResultPushingAction'] = _CAREGIVERRESULTPUSHINGACTION
DESCRIPTOR.message_types_by_name['CaregiverResultPushingResponse'] = _CAREGIVERRESULTPUSHINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CaregiverResultPushingAction = _reflection.GeneratedProtocolMessageType('CaregiverResultPushingAction', (_message.Message,), {
  'DESCRIPTOR' : _CAREGIVERRESULTPUSHINGACTION,
  '__module__' : 'alco_pb2'
  # @@protoc_insertion_point(class_scope:alco.CaregiverResultPushingAction)
  })
_sym_db.RegisterMessage(CaregiverResultPushingAction)

CaregiverResultPushingResponse = _reflection.GeneratedProtocolMessageType('CaregiverResultPushingResponse', (_message.Message,), {
  'DESCRIPTOR' : _CAREGIVERRESULTPUSHINGRESPONSE,
  '__module__' : 'alco_pb2'
  # @@protoc_insertion_point(class_scope:alco.CaregiverResultPushingResponse)
  })
_sym_db.RegisterMessage(CaregiverResultPushingResponse)


DESCRIPTOR._options = None

_CAREGIVERRESULT = _descriptor.ServiceDescriptor(
  name='CaregiverResult',
  full_name='alco.CaregiverResult',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=218,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='push_result',
    full_name='alco.CaregiverResult.push_result',
    index=0,
    containing_service=None,
    input_type=_CAREGIVERRESULTPUSHINGACTION,
    output_type=_CAREGIVERRESULTPUSHINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAREGIVERRESULT)

DESCRIPTOR.services_by_name['CaregiverResult'] = _CAREGIVERRESULT

# @@protoc_insertion_point(module_scope)
